### ISSUE TITLE
No sirve liga de temario en el Readme, master

### ISSUE THREAD

**Issue by 123972** [ITAM-DS/Propedeutico#4]
Al dar clic al vínculo del temario dice que el archivo ya no se encuentra ahí:

https://github.com/ITAM-DS/Propedeutico

https://www.dropbox.com/s/mbckqr2p197w6no/PropedeuticoMCD-Temario.pdf?dl=0

**Comment by palmoreck** [comment]
listo 527d1f418b710af6fc984e37a4b47e25ec37a226
 gracias
